### PR TITLE
Use CMake to build

### PR DESCRIPTION
**Pull request by mhsjlw**
- Requires CMake to build (3.0 version lock should be fine, though)
- No longer uses rom1504/leveldb-mcpe
- Grabs the sources using CMake ExternalProject (no more git submodules!)

Builds are now around 2x faster!

### CODE REVIEW

**Comment by rom1504** [comment]
So they fixed stuff in upstream (and that's why you don't need my fork anymore ?)
About cmake : it's equivalent to a submodule since you're hard coding the commit hash too, but why not.

**Comment by mhsjlw** [comment]
Yes, it successfully builds on macOS (although there is a warning that they'll fix in 10.12). Not sure if it builds on Linux,  so I've left it open to test that.

**Comment by rom1504** [comment]
Oh ok, I'll test it when I'm on a computer

**Comment by mhsjlw** [comment]
Good thing to note: CMake-js attempts to use Ninja if it is available on your system; it appears that it doesn't properly do dependency resolution and fails to build and link leveldb-mcpe, I have added the `-m` flag and that appears to fix it (will update this PR)

**Comment by rom1504** [comment]
broken on linux
Suggestion : add a circle ci thing so you can test on linux

**Comment by mhsjlw** [comment]
Ok, we'll close this and just use #8

**Pull request closed without merging**
